---

- name: "Disable apparmor in grub configuration"
  lineinfile:
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"'
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=.*"
    state: present
    path: /etc/default/grub
  register: grub_cmdline

- name: "Re-generate grub configuration"
  shell: update-grub
  when: grub_cmdline.changed

- name: "Reboot server for disable apparmor in kernel"
  shell: sleep 2 && reboot
  async: 100
  poll: 0
  ignore_errors: true
  when: grub_cmdline.changed

- name: "Wait for server {{ inventory_hostname }} up"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ ssh_port }}"
    delay: 5
    timeout: 60
  delegate_to: localhost
  when: grub_cmdline.changed

- name: "Remove audit daemon configuration"
  file:
    path: /etc/audit/auditd.conf
    state: absent

- name: "Restart services for apply changes"
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - apparmor
    - auditd

- name: "Uninstall apparmor from system"
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3200
    state: absent
    autoremove: yes
    autoclean: yes
  with_items:
    - auditd
    - apparmor
    - apparmor-profiles


